name: notes_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.6
  encrypt: ^5.0.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  google_sign_in: ^6.2.2
  riverpod_annotation: ^2.6.1
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  build_runner: ^2.4.11

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
